const moviesData = [
  {
    title: "The Shawshank Redemption",
    director: "Frank Darabont",
    year: 1994,
    topActors: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
  },
  {
    title: "Inception",
    director: "Christopher Nolan",
    year: 2010,
    topActors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
  },
  {
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    year: 1994,
    topActors: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
  },
  {
    title: "The Godfather",
    director: "Francis Ford Coppola",
    year: 1972,
    topActors: ["Marlon Brando", "Al Pacino", "James Caan"],
  },
  {
    title: "Avengers: Endgame",
    director: "Anthony and Joe Russo",
    year: 2019,
    topActors: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
  },
  {
    title: "Schindler's List",
    director: "Steven Spielberg",
    year: 1993,
    topActors: ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes"],
  },
  {
    title: "Parasite",
    director: "Bong Joon-ho",
    year: 2019,
    topActors: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
  },
  {
    title: "Casablanca",
    director: "Michael Curtiz",
    year: 1942,
    topActors: ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid"],
  },
  {
    title: "The Matrix",
    director: "The Wachowskis",
    year: 1999,
    topActors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
  },
  {
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    year: 1994,
    topActors: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
  },
  {
    title: "La La Land",
    director: "Damien Chazelle",
    year: 2016,
    topActors: ["Ryan Gosling", "Emma Stone", "John Legend"],
  },
  {
    title: "The Silence of the Lambs",
    director: "Jonathan Demme",
    year: 1991,
    topActors: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
  },
  {
    title: "Gladiator",
    director: "Ridley Scott",
    year: 2000,
    topActors: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
  },
  {
    title: "The Dark Knight",
    director: "Christopher Nolan",
    year: 2008,
    topActors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
  },
  {
    title: "Titanic",
    director: "James Cameron",
    year: 1997,
    topActors: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
  },
  {
    title: "Goodfellas",
    director: "Martin Scorsese",
    year: 1990,
    topActors: ["Robert De Niro", "Ray Liotta", "Joe Pesci"],
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    director: "Peter Jackson",
    year: 2003,
    topActors: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
  },
  {
    title: "Jurassic Park",
    director: "Steven Spielberg",
    year: 1993,
    topActors: ["Sam Neill", "Laura Dern", "Jeff Goldblum"],
  },
  {
    title: "The Green Mile",
    director: "Frank Darabont",
    year: 1999,
    topActors: ["Tom Hanks", "Michael Clarke Duncan", "David Morse"],
  },
  {
    title: "Interstellar",
    director: "Christopher Nolan",
    year: 2014,
    topActors: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
  },
  {
    title: "The Departed",
    director: "Martin Scorsese",
    year: 2006,
    topActors: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"],
  },
  {
    title: "The Lion King",
    director: "Roger Allers, Rob Minkoff",
    year: 1994,
    topActors: ["James Earl Jones", "Matthew Broderick", "Jeremy Irons"],
  },
  {
    title: "Fight Club",
    director: "David Fincher",
    year: 1999,
    topActors: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
  },
  {
    title: "The Usual Suspects",
    director: "Bryan Singer",
    year: 1995,
    topActors: ["Kevin Spacey", "Gabriel Byrne", "Chazz Palminteri"],
  },
  {
    title: "Saving Private Ryan",
    director: "Steven Spielberg",
    year: 1998,
    topActors: ["Tom Hanks", "Matt Damon", "Tom Sizemore"],
  },
  {
    title: "The Sixth Sense",
    director: "M. Night Shyamalan",
    year: 1999,
    topActors: ["Bruce Willis", "Haley Joel Osment", "Toni Collette"],
  },
  {
    title: "The Avengers",
    director: "Joss Whedon",
    year: 2012,
    topActors: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
  },
  {
    title: "Eternal Sunshine of the Spotless Mind",
    director: "Michel Gondry",
    year: 2004,
    topActors: ["Jim Carrey", "Kate Winslet", "Kirsten Dunst"],
  },
  {
    title: "Avatar",
    director: "James Cameron",
    year: 2009,
    topActors: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
  },
  {
    title: "The Pianist",
    director: "Roman Polanski",
    year: 2002,
    topActors: ["Adrien Brody", "Thomas Kretschmann", "Frank Finlay"],
  },
  {
    title: "The Truman Show",
    director: "Peter Weir",
    year: 1998,
    topActors: ["Jim Carrey", "Laura Linney", "Noah Emmerich"],
  },
  {
    title: "Inglourious Basterds",
    director: "Quentin Tarantino",
    year: 2009,
    topActors: ["Brad Pitt", "Christoph Waltz", "Mélanie Laurent"],
  },
  {
    title: "Back to the Future",
    director: "Robert Zemeckis",
    year: 1985,
    topActors: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson"],
  },
  {
    title: "The Social Network",
    director: "David Fincher",
    year: 2010,
    topActors: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake"],
  },
  {
    title: "The Grand Budapest Hotel",
    director: "Wes Anderson",
    year: 2014,
    topActors: ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric"],
  },
  {
    title: "The Shining",
    director: "Stanley Kubrick",
    year: 1980,
    topActors: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd"],
  },
  {
    title: "Whiplash",
    director: "Damien Chazelle",
    year: 2014,
    topActors: ["Miles Teller", "J.K. Simmons", "Melissa Benoist"],
  },
  {
    title: "The Prestige",
    director: "Christopher Nolan",
    year: 2006,
    topActors: ["Hugh Jackman", "Christian Bale", "Michael Caine"],
  },
  {
    title: "Memento",
    director: "Christopher Nolan",
    year: 2000,
    topActors: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano"],
  },
  {
    title: "The Terminator",
    director: "James Cameron",
    year: 1984,
    topActors: ["Arnold Schwarzenegger", "Linda Hamilton", "Michael Biehn"],
  },
  {
    title: "A Beautiful Mind",
    director: "Ron Howard",
    year: 2001,
    topActors: ["Russell Crowe", "Ed Harris", "Jennifer Connelly"],
  },
  {
    title: "Spirited Away",
    director: "Hayao Miyazaki",
    year: 2001,
    topActors: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
  },
  {
    title: "The Breakfast Club",
    director: "John Hughes",
    year: 1985,
    topActors: ["Emilio Estevez", "Judd Nelson", "Molly Ringwald"],
  },
  {
    title: "Blade Runner",
    director: "Ridley Scott",
    year: 1982,
    topActors: ["Harrison Ford", "Rutger Hauer", "Sean Young"],
  },
  {
    title: "The Silence of the Lambs",
    director: "Jonathan Demme",
    year: 1991,
    topActors: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
  },
  {
    title: "The Revenant",
    director: "Alejandro González Iñárritu",
    year: 2015,
    topActors: ["Leonardo DiCaprio", "Tom Hardy", "Domhnall Gleeson"],
  },
  {
    title: "Citizen Kane",
    director: "Orson Welles",
    year: 1941,
    topActors: ["Orson Welles", "Joseph Cotten", "Dorothy Comingore"],
  },
  {
    title: "The Big Lebowski",
    director: "Joel Coen, Ethan Coen",
    year: 1998,
    topActors: ["Jeff Bridges", "John Goodman", "Julianne Moore"],
  },
  {
    title: "Apocalypse Now",
    director: "Francis Ford Coppola",
    year: 1979,
    topActors: ["Martin Sheen", "Marlon Brando", "Robert Duvall"],
  },
];

export default moviesData;
